### ISSUE TITLE
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/layer-tls#48]
hitting this http://paste.ubuntu.com/23118148/

**Comment by jamesbeedy** [comment]
I think this is happening because I have two charms in my model that include layer:tls, both exhibit this same error. The tls interface looks to be scoped to unit .... would a modification of https://github.com/juju-solutions/interface-tls/blob/master/peers.py#L10 to 'scope = scopes.SERVICE' be a fix here?

**Comment by jamesbeedy** [comment]
I just figured it out....ahhgg

when I build my charm that includes layer-tls, the config.yaml that is rendered in the built artifact, which also has the configs merged in defined by the included layers.

My built charm's config.yaml shows
```yaml
options:
  "root_certificate":
    "type": "string"
    "default": !!null ""
    "description": |
      The root certificate to use for this grouping of charms.
      If empty (default) the leader will generate a self signed Certificate
      Authority (CA). All certificates will be based on the root certificate.
```

Even though the default config specified by layer-tls is
```yaml
# layer-tls:config.yaml

options:
  root_certificate:
    type: string
    default: ""
    description: |
        The root certificate to use for this grouping of charms.
        If empty (default) the leader will generate a self signed Certificate
        Authority (CA). All certificates will be based on the root certificate.
```

My charm errors on install if I don't explicitly set root_certificate to "" in my charm config on deployment. 

```yaml
# prm.yaml
prm-web:
  root_certificate: ""
```

I think this has to do with the null default that is rendered to the config.yaml of the built charm needing to be overridden by the actual empty string value. Oddly enough, this just started happening, and I've been building these charms with layer-tls for the past few weeks... hrmm
